secondtech/accounts/urls.py
from django.urls import path

from accounts.views import details_profile, register_user, login_user, logout_user, delete_profile, edit_profile, \
    change_password, edit_comment, delete_comment

urlpatterns = [

    path('login/', login_user, name='login user'),
    path('logout/', logout_user, name='logout user'),
    path('register/', register_user, name='register user'),

    path('profile/<int:pk>/', details_profile, name='user profile'),
    path('delete/<int:pk>', delete_profile, name='delete profile'),
    path('edit/<int:pk>', edit_profile, name='edit profile'),
    path('change-password/<int:pk>', change_password, name='change password'),

    path('edit-comment/<int:pk>', edit_comment, name='edit comment'),
    path('delete-comment/<int:pk>', delete_comment, name='delete comment'),

]

secondtech/secondtech/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

                  path('admin/', admin.site.urls),
                  path('', include('secondtech_app.urls')),
                  path('accounts/', include('accounts.urls')),
                  path('custom-admin/', include('secondtech_custom_admin.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

secondtech/secondtech_app/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Device(models.Model):
    SMARTPHONE = 'Smartphone'
    TABLET = 'Tablet'
    LAPTOP = 'Laptop'

    DEVICE_TYPE = (
        (SMARTPHONE, 'Smartphone'),
        (TABLET, 'Tablet'),
        (LAPTOP, 'Laptop')
    )

    title = models.CharField(blank=False, max_length=100)
    image = models.ImageField(upload_to='devices')
    description = models.TextField(max_length=500)
    type = models.CharField(max_length=10, choices=DEVICE_TYPE)
    brand = models.CharField(max_length=50, blank=False)
    model = models.CharField(max_length=50, blank=False)
    storage_capacity = models.IntegerField(blank=False)
    ram = models.IntegerField(blank=False)
    cpu_speed = models.FloatField(blank=False)
    os = models.CharField(max_length=50, blank=False)
    price = models.FloatField(blank=False)
    color = models.CharField(max_length=50, blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.title}"

    def get_price(self):
        return f"{self.price:.2f}"

secondtech/templates/custom-admin/admin_all_comments.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
    <div class="container d-flex justify-content-center pb-5">
        <h1>Hello, Admin</h1>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Creation Date</th>
            <th scope="col">Comment Submitter</th>
            <th scope="col">Comment Receiver</th>
            <th style="width: 20px"></th>
            <th style="width: 20px"></th>
            <th style="width: 20px"></th>
        </tr>
        </thead>
        <tbody>
        {% for comment in comments %}
        <tr>
            <th scope="row"><a href="{% url 'admin view comment' comment.id %}">{{ comment.id }}</a></th>
            <td>{{ comment.created_date }}</td>
            <td><a class="font-weight-bold" href="{% url 'user profile' comment.submitter.id %}">{{ comment.submitter }}</a></td>
            <td><a class="font-weight-bold" href="{% url 'user profile' comment.receiver.id %}">{{ comment.receiver }}</a></td>
            <td><a class="btn btn-info font-weight-bold" href="{% url 'admin view comment' comment.id %}">View</a></td>
            <td><a class="btn btn-warning font-weight-bold" href="{% url 'edit comment' comment.id %}">Edit</a></td>
            <td><a class="btn btn-danger font-weight-bold" href="{% url 'delete comment' comment.id %}">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

secondtech/templates/custom-admin/admin_all_devices.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
    <div class="container d-flex justify-content-center pb-5">
        <h1>Hello, Admin</h1>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Image</th>
            <th scope="col">Title</th>
            <th scope="col">Type</th>
            <th scope="col">Price</th>
            <th scope="col">Uploaded by</th>
            <th style="width: 20px"></th>
            <th style="width: 20px"></th>
            <th style="width: 20px"></th>
        </tr>
        </thead>
        <tbody>
        {% for device in devices %}
        <tr>
            <th scope="row"><a href="{% url 'details device' device.id %}">{{ device.id }}</a></th>
            <td><img width="30" src="{{ device.image.url }}" alt="device image"></td>
            <td>{{ device.title }}</td>
            <td>{{ device.type }}</td>
            <td>{{ device.price }}$</td>
            <td><a class="font-weight-bold" href="{% url 'user profile' device.user.id %}">{{ device.user }}</a></td>
            <td><a class="btn btn-primary font-weight-bold" href="{% url 'details device' device.id %}">View</a></td>
            <td><a class="btn btn-warning font-weight-bold" href="{% url 'edit device' device.id %}">Edit</a></td>
            <td><a class="btn btn-danger font-weight-bold" href="{% url 'delete device' device.id %}">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

secondtech/templates/custom-admin/admin_all_devices_current_user.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
    <div class="container d-flex justify-content-center pb-5">
        <h1>Hello, Admin</h1>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Image</th>
            <th scope="col">Title</th>
            <th scope="col">Type</th>
            <th scope="col">Price</th>
            <th scope="col">Uploaded by</th>
            <th style="width: 20px"></th>
            <th style="width: 20px"></th>
            <th style="width: 20px"></th>
        </tr>
        </thead>
        <tbody>
        {% for device in devices %}
        <tr>
            <th scope="row"><a href="{% url 'details device' device.id %}">{{ device.id }}</a></th>
            <td><img width="30" src="{{ device.image.url }}" alt="device image"></td>
            <td>{{ device.title }}</td>
            <td>{{ device.type }}</td>
            <td>{{ device.get_price }}$</td>
            <td><a class="font-weight-bold" href="{% url 'user profile' device.user.id %}">{{ device.user }}</a></td>
            <td><a class="btn btn-primary font-weight-bold" href="{% url 'details device' device.id %}">View</a></td>
            <td><a class="btn btn-warning font-weight-bold" href="{% url 'edit device' device.id %}">Edit</a></td>
            <td><a class="btn btn-danger font-weight-bold" href="{% url 'delete device' device.id %}">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

secondtech/templates/custom-admin/admin_all_users.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
    <div class="container d-flex justify-content-center pb-5">
        <h1>Hello, Admin</h1>
    </div>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Photo</th>
            <th scope="col">Username</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Email</th>
            <th scope="col">Location</th>
            <th scope="col">Phone Number</th>
            <th scope="col">Total listings from user</th>
            <th style="width: 20px"></th>
            <th style="width: 20px"></th>
            <th style="width: 20px"></th>
        </tr>
        </thead>
        <tbody>
        {% for user in users %}
        <tr>
            <th scope="row"><a href="{% url 'user profile' user.id %}">{{ user.id }}</a></th>
            <td><img width="30" src="{{ user.userprofile.profile_picture.url }}" alt="user image"></td>
            <td>{{ user.username }}</td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.userprofile.location }}</td>
            <td>{{ user.userprofile.phone_number }}</td>
            <td><a class ="font-weight-bold" href="{% url 'admin all devices current user' user.id %}">{{ user.device_set.count }}</a></td>
            <td><a class="btn btn-primary font-weight-bold" href="{% url 'user profile' user.id %}">View</a></td>
            <td><a class="btn btn-warning font-weight-bold" href="{% url 'edit profile' user.id %}">Edit</a></td>
            <td><a class="btn btn-danger font-weight-bold" href="{% url 'delete profile' user.id %}">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

secondtech/templates/custom-admin/admin_landing_page.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
    <div class="text-center pb-5">
        <h1 class="mb-5">Hello, Admin</h1>
    </div>
    <div class="container">
        <div class="row align-items-center justify-content-center">
            <div class="col-md-2">
                <a href="{% url 'admin all users' %}" class="btn btn-sq-lg btn-primary">
                    All Users
                </a>
            </div>
            <div class="col-md-2">
                <a href="{% url 'admin all devices' %}" class="btn btn-sq-lg btn-primary">
                    All Devices
                </a>
            </div>
            <div class="col-md-2">
                <a href="{% url 'admin all comments' %}" class="btn btn-sq-lg btn-primary">
                    All Comments
                </a>
            </div>
        </div>
    </div>
{% endblock %}

secondtech/templates/custom-admin/admin_view_comment.html
{% extends 'shared/base.html' %}
{% load static %}
{% block stylesheet%}<link rel="stylesheet" href="/static/css/profile.css">{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="comments">
                <div class="comment-box">
                            <span class="commenter-pic">
                                <img class="commenter-pic"
                                     src="{{ comment.submitter.userprofile.profile_picture.url }}"
                                     alt="photo">
                                </span>
                    {% if user.is_superuser or user == comment.submitter or user == comment.receiver %}
                        <a class="btn btn-danger float-right ml-2"
                           href="{% url 'delete comment' comment.id %}">Delete</a>
                    {% endif %}
                    {% if user.is_superuser or user == comment.submitter %}
                        <a class="btn btn-primary float-right" href="{% url 'edit comment' comment.id %}">Edit</a>
                    {% endif %}
                    <span class="commenter-name">
                                <a href="{% url 'user profile' comment.submitter.pk %}">{{ comment.submitter }}</a>
                                    <span
                                            class="comment-time">{{ comment.created_date }}
                                    </span>
                                </span>
                    <p class="comment-txt more pl-5">{{ comment.text }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}